-- Create tables
CREATE TABLE IF NOT EXISTS ingredients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL,
  carbon_footprint FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS recipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ingredients_to_recipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  amount FLOAT NOT NULL,
  recipe_id BIGINT REFERENCES recipes(id) ON DELETE CASCADE,
  ingredient_id BIGINT REFERENCES ingredients(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ingredients_home (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  amount FLOAT NOT NULL,
  ingredient_id BIGINT REFERENCES ingredients(id) ON DELETE CASCADE
);

-- Enable Row Level Security (RLS)
ALTER TABLE ingredients ENABLE ROW LEVEL SECURITY;
ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingredients_to_recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE ingredients_home ENABLE ROW LEVEL SECURITY;

-- Create policies for public access (for now)
CREATE POLICY "Public can read ingredients" ON ingredients
  FOR SELECT USING (true);

CREATE POLICY "Public can insert ingredients" ON ingredients
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Public can read recipes" ON recipes
  FOR SELECT USING (true);

CREATE POLICY "Public can insert recipes" ON recipes
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Public can read ingredients_to_recipes" ON ingredients_to_recipes
  FOR SELECT USING (true);

CREATE POLICY "Public can insert ingredients_to_recipes" ON ingredients_to_recipes
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Public can read ingredients_home" ON ingredients_home
  FOR SELECT USING (true);

CREATE POLICY "Public can insert ingredients_home" ON ingredients_home
  FOR INSERT WITH CHECK (true); 